-- MySQL Script generated by MySQL Workbench
-- Sun Jun 10 15:42:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`pratica_exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pratica_exercicio` (
  `idpratica_exercicio` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `obs` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idpratica_exercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `peso` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `objetivo` INT NOT NULL,
  `obs` VARCHAR(100) NULL,
  `administrador_idadministrador` INT NOT NULL,
  `pratica_exercicio_idpratica_exercicio` INT NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_administrador_idx` (`administrador_idadministrador` ASC),
  INDEX `fk_usuarios_pratica_exercicio1_idx` (`pratica_exercicio_idpratica_exercicio` ASC),
  CONSTRAINT `fk_usuarios_administrador`
    FOREIGN KEY (`administrador_idadministrador`)
    REFERENCES `tcc`.`administrador` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_pratica_exercicio1`
    FOREIGN KEY (`pratica_exercicio_idpratica_exercicio`)
    REFERENCES `tcc`.`pratica_exercicio` (`idpratica_exercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`grupo` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`receitas` (
  `idreceitas` INT NOT NULL AUTO_INCREMENT,
  `receita` LONGTEXT NOT NULL,
  `grupo_idgrupo` INT NOT NULL,
  `administrador_idadministrador` INT NOT NULL,
  PRIMARY KEY (`idreceitas`),
  INDEX `fk_receitas_grupo1_idx` (`grupo_idgrupo` ASC),
  INDEX `fk_receitas_administrador1_idx` (`administrador_idadministrador` ASC),
  CONSTRAINT `fk_receitas_grupo1`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `tcc`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receitas_administrador1`
    FOREIGN KEY (`administrador_idadministrador`)
    REFERENCES `tcc`.`administrador` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`unidade_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`unidade_medida` (
  `idmedida` INT NOT NULL AUTO_INCREMENT,
  `medida` VARCHAR(45) NOT NULL,
  `gramas` FLOAT NOT NULL,
  PRIMARY KEY (`idmedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`alimento_quantidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`alimento_quantidade` (
  `alimento_tipo_idalimento_tipo` INT NOT NULL,
  `caloria` FLOAT NOT NULL,
  `proteina` FLOAT NOT NULL,
  `carboidrato` FLOAT NOT NULL,
  `numero_quantidade` FLOAT NOT NULL,
  `nome_alimento` VARCHAR(45) NOT NULL,
  `unidade_medida_idmedida` INT NOT NULL,
  PRIMARY KEY (`alimento_tipo_idalimento_tipo`, `unidade_medida_idmedida`),
  INDEX `fk_alimento_quantidade_unidade_medida1_idx` (`unidade_medida_idmedida` ASC),
  UNIQUE INDEX `caloria_UNIQUE` (`caloria` ASC),
  CONSTRAINT `fk_alimento_quantidade_unidade_medida1`
    FOREIGN KEY (`unidade_medida_idmedida`)
    REFERENCES `tcc`.`unidade_medida` (`idmedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`alimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`alimentacao` (
  `idalimentacao` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `alimento_quantidade_alimento_tipo_idalimento_tipo` INT NOT NULL,
  `alimento_quantidade_unidade_medida_idmedida` INT NOT NULL,
  `caloria` FLOAT NOT NULL,
  `proteina` FLOAT NOT NULL,
  `carboidrato` FLOAT NOT NULL,
  `refeicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalimentacao`),
  INDEX `fk_alimentacao_alimento_quantidade1_idx` (`alimento_quantidade_alimento_tipo_idalimento_tipo` ASC, `alimento_quantidade_unidade_medida_idmedida` ASC),
  CONSTRAINT `fk_alimentacao_alimento_quantidade1`
    FOREIGN KEY (`alimento_quantidade_alimento_tipo_idalimento_tipo` , `alimento_quantidade_unidade_medida_idmedida`)
    REFERENCES `tcc`.`alimento_quantidade` (`alimento_tipo_idalimento_tipo` , `unidade_medida_idmedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`historico` (
  `idhistorico` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `alimentacao_idalimentacao` INT NOT NULL,
  PRIMARY KEY (`idhistorico`, `usuarios_idusuarios`, `alimentacao_idalimentacao`),
  INDEX `fk_historico_usuarios1_idx` (`usuarios_idusuarios` ASC),
  INDEX `fk_historico_alimentacao1_idx` (`alimentacao_idalimentacao` ASC),
  CONSTRAINT `fk_historico_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `tcc`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_alimentacao1`
    FOREIGN KEY (`alimentacao_idalimentacao`)
    REFERENCES `tcc`.`alimentacao` (`idalimentacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`orientacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`orientacao` (
  `idorientacao` INT NULL AUTO_INCREMENT,
  `qunatidade_agua` INT NOT NULL,
  `calorias_dia` FLOAT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `proteina_dia` FLOAT NOT NULL,
  `carboidrato_dia` FLOAT NOT NULL,
  PRIMARY KEY (`idorientacao`, `usuarios_idusuarios`),
  INDEX `fk_orientacao_usuarios1_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_orientacao_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `tcc`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
